# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1648, 903)
        MainWindow.setStyleSheet("font:20px\n"
"")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setStyleSheet("background-color:rgb(0, 152, 213);\n"
"border:0px;\n"
"")   
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/shape 1@2x.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font:20px;\n"
"color:white")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setStyleSheet("QPushButton:pressed{\n"
"background-color:rgb(223, 223, 223)\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(223, 223, 223)\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/rectangle 10 copy 2@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("images/rectangle 10 copy 2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(11, 11))
        self.pushButton.setCheckable(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setStyleSheet("QPushButton:pressed{\n"
"background-color:rgb(223, 223, 223)\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(223, 223, 223)\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/rectangle 8 copy@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(11, 11))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setStyleSheet("QPushButton:pressed{\n"
"background-color:rgb(223, 223, 223)\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(223, 223, 223)\n"
"}")    
# 0, 152, 213

        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/cross 6@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(11, 11))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_14.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(380, 50))
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:2px solid rgb(213, 213, 213);\n"
"border-radius:7px;\n"
"}\n"
"QLineEdit:hover{\n"
"border:4px solid rgb(154, 154, 154);\n"
"border-radius:7px\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/crime.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.Crime_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Crime_comboBox.sizePolicy().hasHeightForWidth())
        self.Crime_comboBox.setSizePolicy(sizePolicy)
        self.Crime_comboBox.setMinimumSize(QtCore.QSize(300, 41))
        self.Crime_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Crime_comboBox.setStyleSheet("QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px\n"
"\n"
"}\n"
"QComboBox:down-arrow {\n"
"          border: none; \n"
"         background: transparent; \n"
"         image: url(\\\"./ui/image/down.png\\\");}\n"
"")
        self.Crime_comboBox.setObjectName("Crime_comboBox")
        self.horizontalLayout_3.addWidget(self.Crime_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("images/zone.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        spacerItem2 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.Region_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Region_comboBox.sizePolicy().hasHeightForWidth())
        self.Region_comboBox.setSizePolicy(sizePolicy)
        self.Region_comboBox.setMinimumSize(QtCore.QSize(300, 41))
        self.Region_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Region_comboBox.setStyleSheet("QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px\n"
"\n"
"}")
        self.Region_comboBox.setObjectName("Region_comboBox")
        self.horizontalLayout_5.addWidget(self.Region_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.District_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.District_comboBox.sizePolicy().hasHeightForWidth())
        self.District_comboBox.setSizePolicy(sizePolicy)
        self.District_comboBox.setMinimumSize(QtCore.QSize(300, 41))
        self.District_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.District_comboBox.setStyleSheet("QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px\n"
"\n"
"}")
        self.District_comboBox.setObjectName("District_comboBox")
        self.horizontalLayout_6.addWidget(self.District_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.Station_comboxBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Station_comboxBox.sizePolicy().hasHeightForWidth())
        self.Station_comboxBox.setSizePolicy(sizePolicy)
        self.Station_comboxBox.setMinimumSize(QtCore.QSize(300, 41))
        self.Station_comboxBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Station_comboxBox.setStyleSheet("QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px\n"
"\n"
"}")
        self.Station_comboxBox.setObjectName("Station_comboxBox")
        self.horizontalLayout_7.addWidget(self.Station_comboxBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.Suburb_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Suburb_comboBox.sizePolicy().hasHeightForWidth())
        self.Suburb_comboBox.setSizePolicy(sizePolicy)
        self.Suburb_comboBox.setMinimumSize(QtCore.QSize(300, 41))
        self.Suburb_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Suburb_comboBox.setStyleSheet("QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px\n"
"\n"
"}")
        self.Suburb_comboBox.setObjectName("Suburb_comboBox")
        self.horizontalLayout_8.addWidget(self.Suburb_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("images/time.png"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        spacerItem3 = QtWidgets.QSpacerItem(330, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("width:80px")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.Year_comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Year_comboBox_1.sizePolicy().hasHeightForWidth())
        self.Year_comboBox_1.setSizePolicy(sizePolicy)
        self.Year_comboBox_1.setMinimumSize(QtCore.QSize(80, 41))
        self.Year_comboBox_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Year_comboBox_1.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}\n"
"")
        self.Year_comboBox_1.setObjectName("Year_comboBox_1")
        self.horizontalLayout_10.addWidget(self.Year_comboBox_1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(20, 0))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("images/lines.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.Year_comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Year_comboBox_2.sizePolicy().hasHeightForWidth())
        self.Year_comboBox_2.setSizePolicy(sizePolicy)
        self.Year_comboBox_2.setMinimumSize(QtCore.QSize(80, 41))
        self.Year_comboBox_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Year_comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Year_comboBox_2.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}\n"
"")
        self.Year_comboBox_2.setDuplicatesEnabled(False)
        self.Year_comboBox_2.setObjectName("Year_comboBox_2")
        self.horizontalLayout_10.addWidget(self.Year_comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.Monthly_comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Monthly_comboBox_1.sizePolicy().hasHeightForWidth())
        self.Monthly_comboBox_1.setSizePolicy(sizePolicy)
        self.Monthly_comboBox_1.setMinimumSize(QtCore.QSize(80, 41))
        self.Monthly_comboBox_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Monthly_comboBox_1.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}\n"
"")
        self.Monthly_comboBox_1.setObjectName("Monthly_comboBox_1")
        self.horizontalLayout_12.addWidget(self.Monthly_comboBox_1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("images/lines.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.Monthly_comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Monthly_comboBox_2.sizePolicy().hasHeightForWidth())
        self.Monthly_comboBox_2.setSizePolicy(sizePolicy)
        self.Monthly_comboBox_2.setMinimumSize(QtCore.QSize(80, 41))
        self.Monthly_comboBox_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Monthly_comboBox_2.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}\n"
"")
        self.Monthly_comboBox_2.setObjectName("Monthly_comboBox_2")
        self.horizontalLayout_12.addWidget(self.Monthly_comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.Quarterly_comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quarterly_comboBox_1.sizePolicy().hasHeightForWidth())
        self.Quarterly_comboBox_1.setSizePolicy(sizePolicy)
        self.Quarterly_comboBox_1.setMinimumSize(QtCore.QSize(80, 41))
        self.Quarterly_comboBox_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Quarterly_comboBox_1.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}")
        self.Quarterly_comboBox_1.setObjectName("Quarterly_comboBox_1")
        self.horizontalLayout_13.addWidget(self.Quarterly_comboBox_1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(30, 0))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("images/lines.png"))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.Quarterly_comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quarterly_comboBox_2.sizePolicy().hasHeightForWidth())
        self.Quarterly_comboBox_2.setSizePolicy(sizePolicy)
        self.Quarterly_comboBox_2.setMinimumSize(QtCore.QSize(80, 41))
        self.Quarterly_comboBox_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Quarterly_comboBox_2.setStyleSheet("\n"
"QComboBox{\n"
"\n"
"    background-color: rgb(233,231,244);\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"    border-radius:7px;\n"
"width:85px\n"
"\n"
"}\n"
"")
        self.Quarterly_comboBox_2.setObjectName("Quarterly_comboBox_2")
        self.horizontalLayout_13.addWidget(self.Quarterly_comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setStyleSheet("border:0px;\n"
"\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(800, 0))
      
        self.frame.setStyleSheet("margin-top:10px;\n"
"margin-bottom:10px;\n"
"border:22px solid rgb(255, 255, 255);\n"
"")    

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 0))

        self.groupBox_2.setStyleSheet("background-color:rgb(0, 152, 213);\n"
        "border-radius:10px;\n"
        "margin-left:8px;\n"
        "margin-right:10px;\n"
        "margin-top:17px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("color:white;}")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Screenshot_pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Screenshot_pushButton_2.sizePolicy().hasHeightForWidth())
        self.Screenshot_pushButton_2.setSizePolicy(sizePolicy)
        self.Screenshot_pushButton_2.setMinimumSize(QtCore.QSize(340, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Screenshot_pushButton_2.setFont(font)
        self.Screenshot_pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(3, 66, 154);\n"
"color:white;\n"
"border-radius:8px;\n"
"margin-left:8px;\n"
"margin-right:10px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:white;\n"
"color:black;\n"
"border-radius:8px\n"
"}")
        self.Screenshot_pushButton_2.setObjectName("Screenshot_pushButton_2")
        self.horizontalLayout_11.addWidget(self.Screenshot_pushButton_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.Screenshot_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Screenshot_pushButton.sizePolicy().hasHeightForWidth())
        self.Screenshot_pushButton.setSizePolicy(sizePolicy)
        self.Screenshot_pushButton.setMinimumSize(QtCore.QSize(340, 65))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Screenshot_pushButton.setFont(font)
        self.Screenshot_pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(3, 66, 154);\n"
"color:white;\n"
"border-radius:8px;\n"
"margin-left:8px;\n"
"margin-right:10px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:white;\n"
"color:black;\n"
"border-radius:8px\n"
"}")
        self.Screenshot_pushButton.setObjectName("Screenshot_pushButton")
        self.horizontalLayout_20.addWidget(self.Screenshot_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        spacerItem7 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem7)
        self.gridLayout_4.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Crime_comboBox.setStyleSheet("QComboBox {"
                                          "width:200px;"
                                          "combobox-popup: 0;\n"  # scroll bar
                                          "background-color: rgb(233, 231, 244);"
                                          "border: 1px solid rgb(200, 200, 200);"
                                          "border-radius: 7px"
                                          "}\n"


                                          "}\n"
                                          "QComboBox:drop-down {"  # Arrow
                                          "width:30px;  "
                                          "height:10px; "
                                          "border: none;  "
                                          "subcontrol-position: right center; "
                                          "subcontrol-origin: padding;"
                                          "image: url(\"images/retangle 4(1).png\");}\n"  # alignment

                                          "QComboBox:drop-down:checked{"
                                          "width:30px;  "
                                          "height:10px; "
                                          "border: none;  "
                                          "subcontrol-position: right center; "
                                          "subcontrol-origin: padding;"
                                          "image: url(\"images/retangle 4.png\");}\n"

                                          "QComboBox QAbstractItemView {"
                                          # "color:black; "
                                          "background: rgb(233, 231, 244); "
                                          "selection-color:white;"
                                          "selection-background-color: rgba(149,125,239,1);"
                                          "}\n"

                                          "QComboBox QAbstractScrollArea QScrollBar:vertical {"
                                          "width:7px;\n"
                                          "height: 100px;"
                                          "background-color: transparent;  }\n"

                                          "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                          "border-radius: 3px;   "
                                          "background: rgba(0,0,0,0.1);}\n"

                                          "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                          "background: rgb(149, 125, 239);}\n"

                                          "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                          "border:none;}"
                                          "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                          "border:none;}"
                                          "")

        self.Region_comboBox.setStyleSheet("QComboBox {"
                                           "combobox-popup: 0;\n"  # Scroll bar setting
                                           "background-color: rgb(233, 231, 244);"
                                           "border: 1px solid rgb(200, 200, 200);"
                                           "border-radius: 7px"
                                           "}\n"

                                           "QComboBox:drop-down {"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4(1).png\");}\n"

                                           "QComboBox:drop-down:checked{"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4.png\");}\n"

                                           "QComboBox QAbstractItemView {"
                                           # "color:black; "
                                           "background: rgb(233, 231, 244); "
                                           "selection-color:white;"
                                           "selection-background-color: rgba(149,125,239,1);"
                                           "}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                           "width:7px;\n"
                                           "height: 100px;"
                                           "background-color: transparent;  }\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                           "border-radius: 3px;   "
                                           "background: rgba(0,0,0,0.1);}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                           "background: rgb(149, 125, 239);}\n"

                                           "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                           "border:none;}"
                                           "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                           "border:none;}"
                                           "")
        self.District_comboBox.setStyleSheet("QComboBox {"
                                             "combobox-popup: 0;\n"  # Scroll bar setting
                                             "background-color: rgb(233, 231, 244);"
                                             "border: 1px solid rgb(200, 200, 200);"
                                             "border-radius: 7px"
                                             "}\n"

                                             "QComboBox:drop-down {"
                                             "width:30px;  "
                                             "height:10px; "
                                             "border: none;  "
                                             "subcontrol-position: right center; "
                                             "subcontrol-origin: padding;"
                                             "image: url(\"images/retangle 4(1).png\");}\n"

                                             "QComboBox:drop-down:checked{"
                                             "width:30px;  "
                                             "height:10px; "
                                             "border: none;  "
                                             "subcontrol-position: right center; "
                                             "subcontrol-origin: padding;"
                                             "image: url(\"images/retangle 4.png\");}\n"

                                             "QComboBox QAbstractItemView {"
                                             # "color:black; "
                                             "background: rgb(233, 231, 244); "
                                             "selection-color:white;"
                                             "selection-background-color: rgba(149,125,239,1);"
                                             "}\n"

                                             "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                             "width:7px;\n"
                                             "height: 100px;"
                                             "background-color: transparent;  }\n"

                                             "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                             "border-radius: 3px;   "
                                             "background: rgba(0,0,0,0.1);}\n"

                                             "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                             "background: rgb(149, 125, 239);}\n"

                                             "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                             "border:none;}"
                                             "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                             "border:none;}"
                                             "")
        self.Station_comboxBox.setStyleSheet("QComboBox {"
                                             "combobox-popup: 0;\n"  # Scroll bar setting
                                             "background-color: rgb(233, 231, 244);"
                                             "border: 1px solid rgb(200, 200, 200);"
                                             "border-radius: 7px"
                                             "}\n"

                                             "QComboBox:drop-down {"
                                             "width:30px;  "
                                             "height:10px; "
                                             "border: none;  "
                                             "subcontrol-position: right center; "
                                             "subcontrol-origin: padding;"
                                             "image: url(\"images/retangle 4(1).png\");}\n"

                                             "QComboBox:drop-down:checked{"
                                             "width:30px;  "
                                             "height:10px; "
                                             "border: none;  "
                                             "subcontrol-position: right center; "
                                             "subcontrol-origin: padding;"
                                             "image: url(\"images/retangle 4.png\");}\n"

                                             "QComboBox QAbstractItemView {"
                                             # "color:black; "
                                             "background: rgb(233, 231, 244); "
                                             "selection-color:white;"
                                             "selection-background-color: rgba(149,125,239,1);"
                                             "}\n"

                                             "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                             "width:7px;\n"
                                             "height: 100px;"
                                             "background-color: transparent;  }\n"

                                             "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                             "border-radius: 3px;   "
                                             "background: rgba(0,0,0,0.1);}\n"

                                             "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                             "background: rgb(149, 125, 239);}\n"

                                             "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                             "border:none;}"
                                             "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                             "border:none;}"
                                             "")

        self.Suburb_comboBox.setStyleSheet("QComboBox {"
                                           "width:200px;"
                                           "combobox-popup: 0;\n"  # Scroll bar setting
                                           "background-color: rgb(233, 231, 244);"
                                           "border: 1px solid rgb(200, 200, 200);"
                                           "border-radius: 7px"
                                           "}\n"

                                           "QComboBox:drop-down {"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4(1).png\");}\n"

                                           "QComboBox:drop-down:checked{"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4.png\");}\n"

                                           "QComboBox QAbstractItemView {"
                                           # "color:black; "
                                           "background: rgb(233, 231, 244); "
                                           "selection-color:white;"
                                           "selection-background-color: rgba(149,125,239,1);"
                                           "}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                           "width:10px;\n"
                                           "height: 400px;"
                                           "background-color: transparent;  }\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                           "border-radius: 3px;   "
                                           "background: rgba(0,0,0,0.1);}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                           "background: rgb(149, 125, 239);}\n"

                                           "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                           "border:none;}"
                                           "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                           "border:none;}"
                                           "")
        self.Year_comboBox_1.setStyleSheet("QComboBox {"
                                           "combobox-popup: 0;\n"  # Scroll bar setting
                                           "background-color: rgb(233, 231, 244);"
                                           "border: 1px solid rgb(200, 200, 200);"
                                           "border-radius: 7px"
                                           "}\n"

                                           "QComboBox:drop-down {"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4(1).png\");}\n"

                                           "QComboBox:drop-down:checked{"
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4.png\");}\n"

                                           "QComboBox QAbstractItemView {"
                                           # "color:black; "
                                           "background: rgb(233, 231, 244); "
                                           "selection-color:white;"
                                           "selection-background-color: rgba(149,125,239,1);"
                                           "}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                           "width:7px;\n"
                                           "height: 100px;"
                                           "background-color: transparent;  }\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                           "border-radius: 3px;   "
                                           "background: rgba(0,0,0,0.1);}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                           "background: rgb(149, 125, 239);}\n"

                                           "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                           "border:none;}"
                                           "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                           "border:none;}"
                                           "")
        self.Year_comboBox_2.setStyleSheet("QComboBox {"
                                           "combobox-popup: 0;\n"  # Scroll bar setting
                                           "background-color: rgb(233, 231, 244);"
                                           "border: 1px solid rgb(200, 200, 200);"
                                           "border-radius: 7px"
                                           "}\n"

                                           "QComboBox:drop-down {"  
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; " 
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4(1).png\");}\n"  

                                           "QComboBox:drop-down:checked{"  
                                           "width:30px;  "
                                           "height:10px; "
                                           "border: none;  "
                                           "subcontrol-position: right center; "  
                                           "subcontrol-origin: padding;"
                                           "image: url(\"images/retangle 4.png\");}\n"  

                                           "QComboBox QAbstractItemView {"  
                                           # "color:black; "
                                           "background: rgb(233, 231, 244); "
                                           "selection-color:white;"
                                           "selection-background-color: rgba(149,125,239,1);"
                                           "}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar:vertical {"  
                                           "width:7px;\n"
                                           "height: 100px;"
                                           "background-color: transparent;  }\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  
                                           "border-radius: 3px;   "
                                           "background: rgba(0,0,0,0.1);}\n"

                                           "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  
                                           "background: rgb(149, 125, 239);}\n"

                                           "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                           "border:none;}"
                                           "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                           "border:none;}"
                                           "")
        self.Monthly_comboBox_1.setStyleSheet("QComboBox {"
                                              "width:70px;"
                                              "combobox-popup: 0;\n"  # Scroll bar setting
                                              "background-color: rgb(233, 231, 244);"
                                              "border: 1px solid rgb(200, 200, 200);"
                                              "border-radius: 7px"
                                              "}\n"

                                              "QComboBox:drop-down {"
                                              "width:30px;  "
                                              "height:10px; "
                                              "border: none;  "
                                              "subcontrol-position: right center; "
                                              "subcontrol-origin: padding;"
                                              "image: url(\"images/retangle 4(1).png\");}\n"

                                              "QComboBox:drop-down:checked{"
                                              "width:30px;  "
                                              "height:10px; "
                                              "border: none;  "
                                              "subcontrol-position: right center; "
                                              "subcontrol-origin: padding;"
                                              "image: url(\"images/retangle 4.png\");}\n"

                                              "QComboBox QAbstractItemView {"
                                              # "color:black; "
                                              "background: rgb(233, 231, 244); "
                                              "selection-color:white;"
                                              "selection-background-color: rgba(149,125,239,1);"
                                              "}\n"

                                              "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                              "width:7px;\n"
                                              "height: 100px;"
                                              "background-color: transparent;  }\n"

                                              "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                              "border-radius: 3px;   "
                                              "background: rgba(0,0,0,0.1);}\n"

                                              "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                              "background: rgb(149, 125, 239);}\n"

                                              "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                              "border:none;}"
                                              "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                              "border:none;}"
                                              "")
        self.Monthly_comboBox_2.setStyleSheet("QComboBox {"
                                              "width:70px;"
                                              "combobox-popup: 0;\n"  # Scroll bar setting
                                              "background-color: rgb(233, 231, 244);"
                                              "border: 1px solid rgb(200, 200, 200);"
                                              "border-radius: 7px"
                                              "}\n"

                                              "QComboBox:drop-down {"
                                              "width:30px;  "
                                              "height:10px; "
                                              "border: none;  "
                                              "subcontrol-position: right center; "
                                              "subcontrol-origin: padding;"
                                              "image: url(\"images/retangle 4(1).png\");}\n"

                                              "QComboBox:drop-down:checked{"
                                              "width:30px;  "
                                              "height:10px; "
                                              "border: none;  "
                                              "subcontrol-position: right center; "
                                              "subcontrol-origin: padding;"
                                              "image: url(\"images/retangle 4.png\");}\n"

                                              "QComboBox QAbstractItemView {"
                                              # "color:black; "
                                              "background: rgb(233, 231, 244); "
                                              "selection-color:white;"
                                              "selection-background-color: rgba(149,125,239,1);"
                                              "}\n"

                                              "QComboBox QAbstractScrollArea QScrollBar:vertical {"
                                              "width:7px;\n"
                                              "height: 100px;"
                                              "background-color: transparent;  }\n"

                                              "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"
                                              "border-radius: 3px;   "
                                              "background: rgba(0,0,0,0.1);}\n"

                                              "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"
                                              "background: rgb(149, 125, 239);}\n"

                                              "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                              "border:none;}"
                                              "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                              "border:none;}"
                                              "")

        self.Quarterly_comboBox_1.setStyleSheet("QComboBox {"
                                                "width:70px;"
                                                "combobox-popup: 0;\n"  # Scroll bar setting
                                                "background-color: rgb(233, 231, 244);"
                                                "border: 1px solid rgb(200, 200, 200);"
                                                "border-radius: 7px"
                                                "}\n"

                                                "QComboBox:drop-down {"
                                                "width:30px;  "
                                                "height:10px; "
                                                "border: none;  "
                                                "subcontrol-position: right center; "
                                                "subcontrol-origin: padding;"
                                                "image: url(\"images/retangle 4(1).png\");}\n"

                                                "QComboBox:drop-down:checked{"
                                                "width:30px;  "
                                                "height:10px; "
                                                "border: none;  "
                                                "subcontrol-position: right center; "
                                                "subcontrol-origin: padding;"
                                                "image: url(\"images/retangle 4.png\");}\n"

                                                "QComboBox QAbstractItemView {"
                                                # "color:black; "
                                                "background: rgb(233, 231, 244); "
                                                "selection-color:white;"
                                                "selection-background-color: rgba(149,125,239,1);"
                                                "}\n"

                                                "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                                "width:7px;\n"
                                                "height: 100px;"
                                                "background-color: transparent;  }\n"

                                                "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                                "border-radius: 3px;   "
                                                "background: rgba(0,0,0,0.1);}\n"

                                                "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                                "background: rgb(149, 125, 239);}\n"

                                                "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                                "border:none;}"
                                                "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                                "border:none;}"
                                                "")
        self.Quarterly_comboBox_2.setStyleSheet("QComboBox {"
                                                "width:70px;"
                                                "combobox-popup: 0;\n"  # Scroll bar setting
                                                "background-color: rgb(233, 231, 244);"
                                                "border: 1px solid rgb(200, 200, 200);"
                                                "border-radius: 7px"
                                                "}\n"

                                                "QComboBox:drop-down {"
                                                "width:30px;  "
                                                "height:10px; "
                                                "border: none;  "
                                                "subcontrol-position: right center; "
                                                "subcontrol-origin: padding;"
                                                "image: url(\"images/retangle 4(1).png\");}\n"

                                                "QComboBox:drop-down:checked{"
                                                "width:30px;  "
                                                "height:10px; "
                                                "border: none;  "
                                                "subcontrol-position: right center; "
                                                "subcontrol-origin: padding;"
                                                "image: url(\"images/retangle 4.png\");}\n"

                                                "QComboBox QAbstractItemView {"
                                                # "color:black; "
                                                "background: rgb(233, 231, 244); "
                                                "selection-color:white;"
                                                "selection-background-color: rgba(149,125,239,1);"
                                                "}\n"

                                                "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # Scroll bar
                                                "width:7px;\n"
                                                "height: 100px;"
                                                "background-color: transparent;  }\n"

                                                "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # Scroll bar
                                                "border-radius: 3px;   "
                                                "background: rgba(0,0,0,0.1);}\n"

                                                "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # scoll 
                                                "background: rgb(149, 125, 239);}\n"

                                                "QComboBox QScrollBar::add-line::vertical{"  # top arrow
                                                "border:none;}"
                                                "QComboBox QScrollBar::sub-line::vertical{"  # down arrow
                                                "border:none;}"
                                                "")
        self.add_shadow1(self.Screenshot_pushButton)
        self.add_shadow1(self.Screenshot_pushButton_2)
        self.add_shadow1(self.groupBox_2)
        # self.add_shadow1(self.groupBox_3)
        self.add_shadow1(self.lineEdit)
        # Dropdown box
        self.add_shadow1(self.Crime_comboBox)
        self.add_shadow1(self.Region_comboBox)
        self.add_shadow1(self.District_comboBox)
        self.add_shadow1(self.Station_comboxBox)
        self.add_shadow1(self.Suburb_comboBox)
        self.add_shadow1(self.Year_comboBox_1)
        self.add_shadow1(self.Year_comboBox_2)
        self.add_shadow1(self.Monthly_comboBox_1)
        self.add_shadow1(self.Monthly_comboBox_2)
        self.add_shadow1(self.Quarterly_comboBox_1)
        self.add_shadow1(self.Quarterly_comboBox_2)
        self.pushButton.clicked.connect(lambda: self.showMinimized())
        self.pushButton_3.clicked.connect(lambda: self.close())
        self.pushButton_2.clicked.connect(self.slot_max_or_recv)
        action = QAction(self)
        action.triggered.connect(self.query)
        action.setIcon(QIcon('./images\search@2x.png'))
        # username.addAction(action, QLineEdit.TrailingPosition)
        # Add imagesture and position
        self.lineEdit.addAction(action, QLineEdit.TrailingPosition)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map"))
        self.label_6.setText(_translate("MainWindow", "   Map"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "abbey,suburb,all,all,all"))
        self.label_9.setText(_translate("MainWindow", "Type"))
        self.label_4.setText(_translate("MainWindow", "Region"))
        self.label_3.setText(_translate("MainWindow", "District"))
        self.label_2.setText(_translate("MainWindow", "Station"))
        self.label_14.setText(_translate("MainWindow", "Suburb"))
        self.label_20.setText(_translate("MainWindow", "Yearly"))
        self.label_21.setText(_translate("MainWindow", "Monthly"))
        self.label_22.setText(_translate("MainWindow", "Quarterly"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">frame 1</span></p></body></html>"))
        self.Screenshot_pushButton_2.setText(_translate("MainWindow", "Summary"))
        self.Screenshot_pushButton.setText(_translate("MainWindow", "Export"))
    def add_shadow1(self, button):
        # add shadow
        self.effect_shadow = QGraphicsDropShadowEffect(self)
        self.effect_shadow.setOffset(-5, 5)  # shift
        self.effect_shadow.setBlurRadius(17)  # shadow radius
        self.effect_shadow.setColor(Qt.gray)  # shadow color
        button.setGraphicsEffect(self.effect_shadow) # inherit to button window
    def slot_max_or_recv(self):
        if self.isMaximized():
            self.showNormal()
        else:
            self.showMaximized()